//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication23
{
    using System;
    using System.Collections.Generic;
    
    public partial class code1
    {
        public int ArticleID { get; set; }
        public string ArticleTitle { get; set; }
        public string ArticleContent { get; set; }
        public string Author { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string filename { get; set; }
        public string image { get; set; }
    }
}
