//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication23
{
    using System;
    using System.Collections.Generic;
    
    public partial class filename
    {
        public string id { get; set; }
        public string file_name { get; set; }
        public string newfilename { get; set; }
        public string uploadpath { get; set; }
    }
}
