//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication23
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class finalEntities1 : DbContext
    {
        public finalEntities1()
            : base("name=finalEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<answer> answer { get; set; }
        public virtual DbSet<concern> concern { get; set; }
        public virtual DbSet<taking> taking { get; set; }
        public virtual DbSet<user_table> user_table { get; set; }
        public virtual DbSet<filename> filename { get; set; }
        public virtual DbSet<code1> code1 { get; set; }
        public virtual DbSet<menus> menus { get; set; }
    }
}
